networks: (( merge ))

jobs:
  - name: server_z1
    templates:
      - name: consul-agent
        release: consul
    instances: 1
    resource_pool: consul
    persistent_disk: 1024
    networks:
      - name: consul
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      network_name: consul
      consul:
        agent:
          mode: server
          servers:
            lan: (( networks.consul.static_ips ))
            wan: (( jobs.server_z2.networks.consul.static_ips jobs.server_z3.networks.consul.static_ips ))
          datacenter: dc1

  - name: server_z2
    templates:
      - name: consul-agent
        release: consul
    instances: 1
    resource_pool: consul
    persistent_disk: 1024
    networks:
      - name: consul
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      network_name: consul
      consul:
        agent:
          mode: server
          servers:
            lan: (( networks.consul.static_ips ))
            wan: (( jobs.server_z1.networks.consul.static_ips jobs.server_z3.networks.consul.static_ips ))
          datacenter: dc2

  - name: server_z3
    templates:
      - name: consul-agent
        release: consul
    instances: 1
    resource_pool: consul
    persistent_disk: 1024
    networks:
      - name: consul
        static_ips: (( merge ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      network_name: consul
      consul:
        agent:
          mode: server
          servers:
            lan: (( networks.consul.static_ips ))
            wan: (( jobs.server_z1.networks.consul.static_ips jobs.server_z2.networks.consul.static_ips ))
          datacenter: dc3

  - name: client
    templates:
      - name: consul-agent
        release: consul
    instances: 5
    resource_pool: consul
    networks:
      - name: consul
    properties:
      network_name: consul
      consul:
        agent:
          servers:
            lan: (( jobs.server_z1.networks.consul.static_ips ))
          datacenter: dc1
          services:
            - name: client
